app:
  name: bff
  image:
    repository: "onecx/onecx-shell-bff"
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          example:
            read: permission on all GET requests and POST search
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
            delete: permission on all DELETE requests